import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Investment from "@/components/Investment";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const bgColor = "#101010";
  const greenColor = "#72E485";
  const lightWhite = "#F8F8F8";
  const yellowOrange = "#F9D658";
  const white = "#FFFFFF";
  const lightGrey = "#EEEDF0";
  const textColorPrimary = "#12164d";
  return (
    <>
      <Head>
        <title>Iradath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-[#101010] w-full h-screen">
        <Navbar />
        <Hero />
      </div>
      <div className="w-full h-screen bg-[#e7e7e7]">
        <About />
      </div>
      <div className="w-full h-screen bg-white">
        <Investment />
      </div>
    </>
  );
}
